spring:
  datasource:
    username: root
    password: 112233456!
    url: jdbc:mysql://182.61.11.218/timeing?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
